package com.gpetuhov.android.sneakeyes;

import android.app.Application;

import com.gpetuhov.android.sneakeyes.dagger.AppComponent;
import com.gpetuhov.android.sneakeyes.dagger.AppModule;
import com.gpetuhov.android.sneakeyes.dagger.DaggerAppComponent;

// SneakEyes application class.
// Builds and keeps instance of AppComponent,
// which is used to inject fields into application activities and fragments
public class SneakEyesApp extends Application {

    // Keeps instance of AppComponent
    private static AppComponent mAppComponent;

    public static AppComponent getAppComponent() {
        return mAppComponent;
    }

    @Override
    public void onCreate() {
        super.onCreate();

        // Initialize sneaking service
        SneakingService.setServiceAlarm(this);

        // Build and keep AppComponent instance.
        // DaggerAppComponent is generated by Dagger.
        mAppComponent = DaggerAppComponent.builder()
                .appModule(new AppModule(this))
                .build();
    }
}
